### ISSUE TITLE
Breaking on latest node v6.0

### ISSUE THREAD

**Issue by binarykitchen** [dodo/node-slug#73]
This because it uses https://github.com/dodo/node-unicodetable which uses bufferstream which is soooo antique.

I guess the solution is to pick another unicode package that goes well on node v6 and/or is frequently updated.

**Comment by Zertz** [comment]
I posted some details [here](https://github.com/dodo/node-slug/pull/70) and forked node-unicodetable to [unicode-json](https://github.com/Zertz/unicode-json). The test suite is identical, except it outputs JSON files instead of a CommonJS modules. Using it here should simply involve swapping modules.

Since @dodo is currently unavailable, I have created a [fork](https://github.com/Zertz/mollusc) compatible with Node 0.12+.

**Comment by binarykitchen** [comment]
I have switched to https://github.com/lovell/limax which works well
